# base line config
# data class variable: variable: value
mode:
  experiment_name: 'base line'

dataset:
  name: "DataSet"

model:
  name: ""

train:
  name: "Trainer"

test:
  name: "Tester"

evaluate:
  name: "Evaluater"